//Lord Jesus Christ, most merciful Saviour of the world, we humbly beseech You, by Your most Sacred Heart, that all the sheep who stray out of Your fold may in one days be converted to You, the Shepherd and Bishop of their souls, who lives and reigns with God the Father in the unity of the Holy Spirit, world without end.  Amen. 
//
//O Father, in the name of Your Son Jesus, and in the power and authority of the Holy Spirit, I ask that You fill all those who come to this site with the knowledge of Your will through all spiritual wisdom and understanding. Enlighten these precious children of Yours, dear Lord! Teach these dear ones to live in a manner that is worthy of You, so as to be fully pleasing to You, full of good works, bearing good fruits and ever growing in knowledge of You. Strengthen these lost lambs, dear Lord, with every power of Your Holy Spirit, in accordance with Your might, for all endurance and patience, with joy, giving thanks to You O Father! Make Your children fit to share in the inheritance of the holy ones in the Light. Deliver these beloved ones from the power of darkness and transfer them all into the kingdom of Your Beloved Son, Jesus, in whom is redemption and the forgiveness of sins. Amen.
//
//Oh glorious patriarch St. Joseph, who merited to be called "just' by the Holy Ghost, I urgently all the souls who visit this site, which Jesus redeemed at the price of his precious blood.  Thou knowest how deplorable is the state and how unhappy the life of those who have banished this loving savior from their hearts, and how greatly they are exposed to the danger of losing him eternally. Permit not, I beseech thee, that all souls visiting here should continue any longer in their evil ways; preserve them from the danger that threatens them; touch the hearts of the prodigal children and conduct them back to the bosom of the fondest of fathers. Abandon them not, I implore thee, till thou hast opened to them the gates of the heavenly city, where they will praise and bless thee throughout eternity for the happiness which they will owe to thy powerful intercession.  Amen.
//
//Hail Mary, full of grace, the Lord is with Thee.  Blessed art thow among women, and blessed is the fruit of thy womb Jesus.  Holy Mary, Mother of God, pray for us sinners now and at the hour of our death.  Amen.
//
//Dear Lord, please bless, protect, convert and save all those who visit this site.  May Your will be done, and may this site be used for Your glory.  Have mercy on your wayward children, and through the most powerful intercession of the Blessed Virgin Mary, I prayer for the salvation of souls and that this site be your success and glory.
//
//Jesus, Mary and Joseph, I love you.  Save souls, and please bring an end to abortion throughout the world.
//
//Eternal Father, I offer you the Body and Blood, Soul and Divinity of Your Dearly Beloved Son, Our Lord, Jesus Christ, in atonement for our sins and those of the whole world.
//For the sake of His sorrowful Passion, have mercy on us and on the whole world.
//
//O Blood and Water which gushed forth from the Heart of Jesus as a Fount of Mercy for us, I trust in you.